runner:
  total_steps: 50000
  gradient_clipping: 1
  gradient_accumulate_steps: 1

  log_step: 500
  eval_step: 10000 # 1000
  save_step: 5000 # 1000
  max_keep: 10
  eval_dataloaders:
    - dev
    - test

optimizer:
  name: AdamW
  lr: 1.0e-4

scheduler:
  name: linear_schedule_with_warmup
  num_warmup_steps: 4000

downstream_expert:
  datarc:
    num_workers: 3
    train_batch_size: 6
    eval_batch_size: 5
    
    adress_data_root: "/content/gdrive/MyDrive/ML_data"
    download: False
    corpus_train_dev: "VCTK"
    corpus_test: "VCC20"
    num_dev_sample: 5
    eval_f0_path: "./downstream/a2o-vc-vcc2020/data/f0.yaml"

    num_target: 10
    len_chunk: null

    fbank_config:
      fs: 24000
      n_mels: 80
      n_fft: 1024
      n_shift: 256
      win_length: null
      window: "hann"
      fmin: 80
      fmax: 7600
      gl_iters: 64

  modelrc:
    hidden_dim: 1024 # Latent between Encoder and Decoder
    # Encoder
    enc_conv_causal: False
    enc_bidi: True
    # Global conditioning
    spk_emb_integration_type: concat # add or concat
    spk_emb_dim: 256
    # Decoder prenet
    prenet_dim: 256
    prenet_layers: 2
    prenet_dropout_rate: 0.5
    # Decoder mainnet
    lstmp_layers: 2
    lstmp_layernorm: False
    lstmp_dropout_rate: 0.2
